include: package:lint/analysis_options.yaml
# include: package:pedantic/analysis_options.yaml

linter:
  rules:
    # Style rules
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_empty_else
    - avoid_null_checks_in_equality_operators
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - camel_case_extensions
    - empty_catches
    - no_duplicate_case_values
    - null_closures
    - omit_local_variable_types
    - prefer_adjacent_string_concatenation
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_single_quotes
    - prefer_spread_collections
    - recursive_getters
    - unawaited_futures
    - unnecessary_null_in_if_null_operators
    - unrelated_type_equality_checks
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
    - camel_case_types
    - library_names
    - file_names
    - library_prefixes
    - non_constant_identifier_names
    - constant_identifier_names
    - directives_ordering
    # - lines_longer_than_80_chars
    - curly_braces_in_flow_control_structures
    - slash_for_doc_comments
    # Usage rules
    - parameter_assignments
    - prefer_interpolation_to_compose_strings
    - prefer_collection_literals
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - prefer_expression_function_bodies
    - prefer_initializing_formals
    - type_init_formals
    - empty_constructor_bodies
    - empty_statements
    - unnecessary_new
    - unnecessary_this
    - unnecessary_const
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_lambdas
    - unnecessary_getters_setters
    - hash_and_equals
    - prefer_relative_imports
    - test_types_in_equals
    - always_put_required_named_parameters_first
    # - public_member_api_docs # prefer
    # - comment_references # Unused because https://github.com/dart-lang/sdk/issues/36974
    # USAGE
    - implementation_imports
    # prefer
    - unnecessary_brace_in_string_interps # avoid
    - prefer_function_declarations_over_variables
    - avoid_unnecessary_containers
    - avoid_catching_errors
    # DESIGN
    - use_to_and_as_if_applicable # prefer
    - one_member_abstracts # avoid
    - avoid_classes_with_only_static_members # avoid
    - prefer_mixin
    - use_setters_to_change_properties
    - avoid_setters_without_getters
    - avoid_returning_null # avoid
    - avoid_returning_this # avoid
    - type_annotate_public_apis # prefer
    # - prefer_typing_uninitialized_variables # consider
    - avoid_types_on_closure_parameters # avoid
    - avoid_return_types_on_setters
    - avoid_private_typedef_functions # prefer
    # - use_function_type_syntax_for_parameters # consider
    - avoid_positional_boolean_parameters # avoid
    - avoid_equals_and_hash_code_on_mutable_classes # avoid
    # - unawaited_futures
    # - cascade_invocations
    - unnecessary_statements
    
analyzer:
  errors:
    missing_required_argument: error
    parameter_assignments: error
    missing_return: error
    sort_pub_dependencies: ignore
    file_names: ignore
    todo: ignore

    